
2. 错误处理
<script>
// (1). 捕获错误 try ... catch
try {
  let d 
  console.log(d.xxx)
} catch(error) {
  console.log(error)
  console.log(error.message)
  console.log(error.stack)
}
console.log('出错之后')

// (2). 抛出错误: throw error
function something() {
  if (Date.now() % 2 === 1) {
    console.log('当前时间为奇数, 可以执行任务')
  } else {
    throw new Error('当前时间为偶数, 不能执行任务')
  }
}

try {
  something()
} catch {
  console.log('捕获了错误')
}

</script>